apiVersion: v1
kind: ConfigMap
metadata:
  name: azure-markdown-reviewer-config
data:
  PORT: "8080"
  AZURE_STORAGE_ENDPOINT: "https://chat8gpteducationaccount.blob.core.windows.net"
  AZURE_STORAGE_CONTAINER: "education"
  AZURE_STORAGE_OUTPUT_PREFIX: "generated/"
